name: Publish
on: [push]
jobs:
  publish:
    if: ${{ github.repository_owner == 'turtton' && !contains(github.event.head_commit.message, '[CI-SKIP]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 18
          cache: gradle

      # Generate the build number based on tags to allow per branch build numbers, not something github provides by default.
      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{ secrets.github_token }}
          prefix: ${{ github.ref }}

      - name: publish
        uses: uTen2c/publish-to-github@v1
        with:
          repo: ${{ secrets.REPO }}
          token-user: ${{ secrets.TOKEN_USER }}
          token: ${{ secrets.TOKEN }}